### ISSUE TITLE
Auto points reset

### ISSUE THREAD

**Issue by Mosquee** [elwint/enduro-cup-tm2#1]
I would like to know if there is any way to reset point after the map number to have a server that run by itself

**Comment by Mosquee** [comment]
Nevermind I found it but where is in the code, the moment which check when the map number is over (/setmaps)

**Comment by elwint** [comment]
It's at https://github.com/elwint/enduro-cup-tm2/blob/master/plugins/plugin.records_eyepiece_enduro.php#L5035 just before showing the points. I didn't plan to work on this plugin anymore, but I've a bit time now so I'll add an option in the config to enable auto reset today :)

**Comment by Mosquee** [comment]
I already added some code on the if $mapdone >= $map section to do that

**Comment by elwint** [comment]
Resetting the points there should idd work. I added it in `re_onBeginMap` instead in case if you want to save the total points for some reason
